06 04 2024
adoppp/wika pull request #3
Opened 2024-04-08 18:25 UTC by adoppp

2024-04-09 10:24 UTC, DmytroZhdanov requested changes

2024-04-09 10:24 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/aboutText/AboutText.tsx
> +        <span className={transition}>
wk_transition-colors потрібно повернути, оскільки в transition не вказаний перелік властивостей які потрібно анімувати

2024-04-09 10:24 UTC, DmytroZhdanov commented on frontend/src/app/layout.tsx
> +        <Suspense fallback={<Loading />}>
Саспенз прибираємо

2024-04-10 10:08 UTC, DmytroZhdanov requested changes

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@about/page.tsx
> +      className="wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px] wk_mx-auto wk_mb-[12px] wk_px-[16px] wk_py-[52px] tablet:wk_px-[68px] tablet:wk_pt-[56px] tablet:wk_pb-[68px] desktop:wk_py-[120px]
У тебе тут зараз максимальна ширина не змінюється від зміни екрану на десктоп. Можеш спробувати взагалі прибрати "wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px]" і спробувати залишити "wk_w-fit". Єдине падінги на боді потрібно перевірити. Якщо не спрацює - поверни як було

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@about/page.tsx
> +          <li className={cn("wk_px-[20px] wk_py-[10px] wk_rounded-25 wk_leading-[calc(18/16)] tablet:wk_text-[20px] tablet:wk_leading-[calc(24/20)] wk_text-th_white wk_bg-[#FFFFFF33] hover:wk_text-th
Поверни назад "wk_transition-colors". Інакше у тебе транзішн не працюватиме оскільки ти не вказуєш яку властивість потрібно анімувати

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@about/page.tsx
> +          <li className={cn("wk_px-[20px] wk_py-[10px] wk_rounded-25 wk_leading-[calc(18/16)] tablet:wk_text-[20px] tablet:wk_leading-[calc(24/20)] wk_text-th_white wk_bg-[#FFFFFF33] hover:wk_text-th
Поверни назад "wk_transition-colors"

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@about/page.tsx
> +          <li className={cn("wk_px-[20px] wk_py-[10px] wk_rounded-25 wk_leading-[calc(18/16)] tablet:wk_text-[20px] tablet:wk_leading-[calc(24/20)] wk_text-th_white wk_bg-[#FFFFFF33] hover:wk_text-th
Поверни назад "wk_transition-colors"

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@burgerMenu/page.tsx
> +    return <BurgerMenu isOpen={showMobMenu} t={t} navT={navT} lng={lng}  />
Немає сенсу виносити мобільне меню в окремий компонент. Перенеси все сюди

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@call/page.tsx
> +    <section className="wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px] wk_mx-auto wk_px-[16px] wk_py-[52px] tablet:wk_px-[68px] tablet:wk_pt-[56px] tablet:wk_pb-[68px] desktop:wk_pt-[120px] deskto
У тебе тут зараз максимальна ширина не змінюється від зміни екрану на десктоп. Можеш спробувати взагалі прибрати "wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px]" і спробувати залишити "wk_w-fit". Єдине падінги на боді потрібно перевірити. Якщо не спрацює - поверни як було

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +    <footer className="wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px] wk_mx-auto wk_px-[12px] wk_py-[48px] desktop:wk_px-[68px] desktop:wk_py-[100px] wk_rounded-50 wk_bg-th_black wk_w-auto">
wk_w-auto, wk_w-fill. Визначся вже з чимось одним

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +              className={cn("wk_flex wk_justify-center wk_items-center wk_size-[35px] tablet:wk_size-[30px] wk_rounded-[4px] wk_bg-th_white wk_transition-colors wk_ease-wk_quart wk_duration-400 hover
transition додав, а "wk_ease-wk_quart wk_duration-400" не прибрав

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +              className={cn("wk_flex wk_justify-center wk_items-center wk_size-[35px] tablet:wk_size-[30px] wk_rounded-[4px] wk_bg-th_white wk_transition-colors wk_ease-wk_quart wk_duration-400 hover
transition додав, а "wk_ease-wk_quart wk_duration-400" не прибрав

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +              className={cn("wk_flex wk_justify-center wk_items-center wk_size-[35px] tablet:wk_size-[30px] wk_rounded-[4px] wk_bg-th_white wk_transition-colors wk_ease-wk_quart wk_duration-400 hover
transition додав, а "wk_ease-wk_quart wk_duration-400" не прибрав

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +          className={cn("wk_transition-colors wk_ease-wk_quart wk_duration-400 hover:wk_text-th_white focus:wk_text-th_white focus:wk_outline-none",
transition додав, а "wk_ease-wk_quart wk_duration-400" не прибрав

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +          className={cn("wk_transition-colors wk_ease-wk_quart wk_duration-400 hover:wk_text-th_white focus:wk_text-th_white focus:wk_outline-none",
transition додав, а "wk_ease-wk_quart wk_duration-400" не прибрав

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@footer/page.tsx
> +          className={cn("wk_transition-colors wk_ease-wk_quart wk_duration-400 hover:wk_text-th_white focus:wk_text-th_white focus:wk_outline-none",
transition додав, а "wk_ease-wk_quart wk_duration-400" не прибрав

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@header/page.tsx
> +        wk_translate-x-[-50%] wk_overflow-hidden
Нащо тут оверфлоу хіден якщо ти винес мобільний меню в лейаут?

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@hero/page.tsx
> +    <section className="wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px] wk_mx-auto wk_mb-[12px] wk_pt-[384px] tablet:wk_pt-[364px] desktop:wk_pt-[308px] wk_pb-[40px] tablet:wk_pb-[86px] desktop:wk_
У тебе тут зараз максимальна ширина не змінюється від зміни екрану на десктоп. Можеш спробувати взагалі прибрати "wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px]" і спробувати залишити "wk_w-fit". Єдине падінги на боді потрібно перевірити. Якщо не спрацює - поверни як було

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@services/page.tsx
> +      className="wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px] wk_mx-auto wk_mb-[12px] wk_px-[16px] wk_py-[52px] tablet:wk_px-[68px] tablet:wk_pt-[56px] tablet:wk_pb-[68px] desktop:wk_pt-[100px]
У тебе тут зараз максимальна ширина не змінюється від зміни екрану на десктоп. Можеш спробувати взагалі прибрати "wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px]" і спробувати залишити "wk_w-fit". Єдине падінги на боді потрібно перевірити. Якщо не спрацює - поверни як було

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/layout.tsx
> +      {burgerMenu}
Такі речі зазвичай рендерять перед закриваючим тегом боді

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +import { Button } from "../button";
Проведи рефакторинг імпортів

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +        <div className={cn(isOpen ? 'wk_-translate-x-[0rem]' : 'wk_translate-x-full', transition, 'wk_w-max wk_h-max wk_fixed wk_top-0 wk_left-0 wk_z-30 desktop:wk_translate-x-full desktop:wk_hidden'
'wk_-translate-x-[0rem]' ??? rem прибери + звідки тире перед translate?
Не вказав які властивості анімувати

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +                <div className=" wk_flex wk_flex-col wk_gap-[79px]">
Нащо пробіл після відкриваючих лапок?

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +                    <div className=" wk_flex wk_gap-[74px] wk_flex-col">
Нащо пробіл після відкриваючих лапок?

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +                        <div>
Нащо кнопку огортати дівом? Прибери його

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/navBar/NavBar.tsx
> +            className=' desktop:wk_hidden wk_size-[40px] wk_inline wk_ml-[4px] group-hover:wk_rotate-[45deg] group-hover:wk_text-gray_500 group-focus:wk_text-gray_500'
Краще не через "desktop:wk_hidden", а через умовний рендер. Ти отримуєш в пропсах location. По ньому можеш робити перевірку. Інакше ці стрілки зʼявляються в футері на мобілці та планшеті

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/navBar/NavBar.tsx
> +            className=' desktop:wk_hidden wk_size-[40px] wk_inline wk_ml-[4px] group-hover:wk_rotate-[45deg] group-hover:wk_text-gray_500 group-focus:wk_text-gray_500'
Краще не через "desktop:wk_hidden", а через умовний рендер. Ти отримуєш в пропсах location. По ньому можеш робити перевірку. Інакше ці стрілки зʼявляються в футері на мобілці та планшеті

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/navBar/NavBar.tsx
> +            className=' desktop:wk_hidden wk_size-[40px] wk_inline wk_ml-[4px] group-hover:wk_rotate-[45deg] group-hover:wk_text-gray_500 group-focus:wk_text-gray_500'
Краще не через "desktop:wk_hidden", а через умовний рендер. Ти отримуєш в пропсах location. По ньому можеш робити перевірку. Інакше ці стрілки зʼявляються в футері на мобілці та планшеті

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/navBar/NavBar.tsx
> +            className=' desktop:wk_hidden wk_size-[40px] wk_inline wk_ml-[4px] group-hover:wk_rotate-[45deg] group-hover:wk_text-gray_500 group-focus:wk_text-gray_500'
Краще не через "desktop:wk_hidden", а через умовний рендер. Ти отримуєш в пропсах location. По ньому можеш робити перевірку. Інакше ці стрілки зʼявляються в футері на мобілці та планшеті

2024-04-10 10:08 UTC, DmytroZhdanov commented on frontend/src/app/loading.tsx
> +      Loading.remove(500)
Нащо затримка?

2024-04-10 12:49 UTC, adoppp commented on frontend/src/app/[lng]/@footer/page.tsx
> +    <footer className="wk_max-w-[calc(100vw-24px)] desktop:wk_w-[1416px] wk_mx-auto wk_px-[12px] wk_py-[48px] desktop:wk_px-[68px] desktop:wk_py-[100px] wk_rounded-50 wk_bg-th_black wk_w-auto">
тут нужно ауто ибо при фите оно будет по ширине элементов грудо говоря, а  тут ауто для того чтобы сам на всю ширину контейнера

2024-04-10 12:54 UTC, adoppp commented on frontend/src/app/[lng]/@header/page.tsx
> +        wk_translate-x-[-50%] wk_overflow-hidden
это я уже заебался и забыл. убрал

2024-04-10 12:55 UTC, adoppp commented on frontend/src/app/[lng]/layout.tsx
> +      {burgerMenu}
знаю, забыл перекинуть

2024-04-10 12:58 UTC, adoppp commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +        <div className={cn(isOpen ? 'wk_-translate-x-[0rem]' : 'wk_translate-x-full', transition, 'wk_w-max wk_h-max wk_fixed wk_top-0 wk_left-0 wk_z-30 desktop:wk_translate-x-full desktop:wk_hidden'
тире это как минус(для любых правил) если так написать то будет -0. у меня написано wk_translate-x-0 хз почему тут так, да и саспенс даже выше остался

2024-04-10 13:00 UTC, adoppp commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
> +                <div className=" wk_flex wk_flex-col wk_gap-[79px]">
я так пишу и забываю убирать. у меня подсказки только после проблема вылезают

2024-04-10 13:09 UTC, adoppp commented on frontend/src/app/loading.tsx
> +      Loading.remove(500)
для того чтобы пользователь хоть немного видел загрузку(пока что загружать нечего) потом уберем если надо будет. + мне было удобнее стили накидывать

2024-04-11 06:13 UTC, DmytroZhdanov reviewed
Спробуй прибрати wk_w-auto з секцій. Бо вони за замовчуванням мають цю властивість. 
Не всі коментарі врахував.
Плюс я додав ще парочку

2024-04-11 06:13 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@burgerMenu/page.tsx
> +                <>
Це можна без фрагменту, а одразу компонент вставляти

2024-04-11 06:13 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@header/page.tsx
> +export default async function Page({ params: { lng }, searchParams }: Readonly<PageProps>) {
Нащо searchParams? Ти їх не використовуєш тут

2024-04-11 06:13 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/navBar/NavBar.tsx
Стрілочки краще взагалі не рендерити в футері, а не просто приховати. Використай умовний рендер замість приховування стилями

2024-04-15 16:26 UTC, DmytroZhdanov requested changes

2024-04-15 16:26 UTC, DmytroZhdanov commented on frontend/src/app/types/global.ts
> +export interface ErrorProps {
Перенеси ці пропси у файл самого ерору. Не має сенсу виносити їх бо зна куди, якщо ти використовуєш їх тільки в одному місці

2024-04-15 16:26 UTC, DmytroZhdanov commented on frontend/src/app/not-found.tsx
> +                    <a className={cn('wk_underline wk_text-th_accent hover:wk_text-hotPink_500 active:wk_text-hotPink_600 focus:wk_text-hotPink_600', transition)} href="https://www.instagram.com/viks
Не прописав які властивості анімуєш

2024-04-15 16:26 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/navBar/NavBar.tsx
Забув виправити згідно із цим коментарем

2024-04-15 16:26 UTC, DmytroZhdanov commented on frontend/src/app/[lng]/@about/page.tsx
> +          <li className={cn("wk_px-[20px] wk_py-[10px] wk_rounded-25 wk_leading-[calc(18/16)] tablet:wk_text-[20px] tablet:wk_leading-[calc(24/20)] wk_text-th_white wk_bg-[#FFFFFF33] hover:wk_text-th
Забув про цей коментар

2024-04-15 21:50 UTC, adoppp commented on frontend/src/app/types/global.ts
> +export interface ErrorProps {
нам может понадобится еще в других ошибках. пускай будет, хуже не станет

2024-04-16 10:13 UTC, DmytroZhdanov approved these changes

2024-04-16 10:14 UTC, merged