Zhdanov/16 04 2024
adoppp/wika pull request #4
Opened 2024-04-17 16:53 UTC by DmytroZhdanov

2024-04-20 17:47 UTC, adoppp commented on frontend/src/app/error.tsx
зачем ты убрал те отступы? я их специально сделал не по макету чтобы не было скролла и выглядело +- норм. еще по поаоду зачем ты убрал с р максимальную ширину? некрасиво будет если текст во всю строку + читать сложнее. как правило больше 1080 не требуется. лучше верни, а не текст на весь экран. или сделац с таблета ограничение

2024-04-20 17:47 UTC, adoppp commented on frontend/src/app/lib/api.ts
раскидай по папкам. типы в типы, константы в константы. иначе смвлс было раскидывать? или создай хоть папку вервайс или сервер ну или апи просто

2024-04-20 17:47 UTC, adoppp commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
я ж специально убрал. смысл импорта? у нас и так адрес будет лнг и все

2024-04-20 17:48 UTC, adoppp requested changes
написал коменты

2024-04-20 18:43 UTC, DmytroZhdanov commented on frontend/src/app/error.tsx
Це невдало конфлікти вирішив. Подивлюсь як було в твоїй гілці і підправлю

2024-04-20 18:43 UTC, DmytroZhdanov commented on frontend/src/app/lib/api.ts
Як на мене цілковитий брєд це робити в утілсах. Але гляну що можна зробити

2024-04-20 18:43 UTC, DmytroZhdanov commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
По-перше якого імпорту? А по-друге, якщо я правильно розумію про що ти, то це теж наслідки вирішення конфліктів

2024-05-02 11:19 UTC, adoppp requested changes
все почти супер. отписал

2024-05-02 11:19 UTC, adoppp commented on frontend/src/app/components/ui/burgerMenu/burgerMenu.tsx
кнопка закрыть была шаблонной, и там был лнг. и зачем ты вернул <><\>? можно просто дизаблпд скролл возвращать

2024-05-02 11:19 UTC, adoppp commented on frontend/src/app/error.tsx
вроде все гут

2024-05-02 11:19 UTC, adoppp commented on frontend/src/app/not-found.tsx
отступы должны быть такие: [140px] tablet:wk_mt-[180px] desktop:wk_mt-[240px]

2024-05-02 11:19 UTC, adoppp commented on frontend/src/app/error.tsx
а нет, так же как и в нот фаунд. вот: [140px] tablet:wk_mt-[180px] desktop:wk_mt-[240px]

2024-05-14 10:18 UTC, merged